# Generated by Django 5.0.7 on 2024-07-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0026_room_capacity_alter_payment_payemnt_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payemnt_type',
            field=models.CharField(choices=[('CASH', 'CASH'), ('PAYTM', 'PAYTM'), ('CARD', 'CARD')], max_length=30),
        ),
    ]
